rasp/check/urls.py
from django.urls import path
from . import views

app_name = 'check'  # Пространство имен для приложения "check"

urlpatterns = [
    path('load', views.load_file_get, name='check_page'),  # GET запрос
    path('load_post', views.load_file_post, name='check_page_post'),  # POST запрос
    path('list_folders/', views.list_folders, name='list_folders'),
    path('list_files/<str:folder>/', views.list_files, name='list_files'),
    path('download/<str:folder>/<str:filename>/', views.download_file, name='download_file'),
    path('download_xml/<str:folder>/<str:filename>/', views.download_file_xml, name='download_file_xml'),
    path('schedule_check/<str:folder>/', views.schedule_check, name='schedule_check'),
    path('list_files/<str:folder>/report/', views.report, name='report'),
    path('rasp_to_db/', views.rasp_to_db, name='rasp_to_db'),
]

rasp/main/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.class_rasp_main, name='class_rasp'),
    path('exam_rasp/', views.exam_rasp_main, name='exam_rasp'),
    path('class_pdf/', views.class_pdf, name='class_pdf'),
    path('exam_pdf/', views.exam_pdf, name='exam_pdf'),
]

rasp/rasp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('check/', include('check.urls'), name='check_page')
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

rasp/check/models.py
from django.db import models


class MyFiles(models.Model):
    file = models.FileField(upload_to='upl_files')
    file_type = models.CharField(max_length=50)
    year = models.CharField(max_length=50)
    semester = models.CharField(max_length=50)
    directory_path = models.CharField(max_length=150)

    def get_file_path(self):
        return self.file.path


class Faculty(models.Model):
    faculty = models.CharField(max_length=200)

    def __str__(self):
        return self.faculty


class Qualification(models.Model):
    qualification = models.CharField(max_length=100)

    def __str__(self):
        return self.qualification


class Group(models.Model):
    group = models.CharField(max_length=100)
    faculty = models.ForeignKey(Faculty, on_delete=models.CASCADE)
    course = models.IntegerField()
    qualification = models.ForeignKey(Qualification, on_delete=models.CASCADE)
    num_students = models.IntegerField()

    class Meta:
        ordering = ['group']

    def __str__(self):
        return self.group


class Weekday(models.Model):
    weekday = models.CharField(max_length=100)

    def __str__(self):
        return self.weekday


class Discipline(models.Model):
    discipline = models.CharField(max_length=100)

    class Meta:
        ordering = ['discipline']

    def __str__(self):
        return self.discipline


class LessonType(models.Model):
    lesson_type = models.CharField(max_length=100)

    def __str__(self):
        return self.lesson_type


class Department(models.Model):
    department = models.CharField(max_length=100)
    department_number = models.IntegerField()

    def __str__(self):
        return str(self.department_number)


class Position(models.Model):
    position = models.CharField(max_length=100)

    def __str__(self):
        return self.position


class Teacher(models.Model):
    full_name = models.CharField(max_length=100, default='')
    short_name = models.CharField(max_length=100, default='')
    position = models.ForeignKey(Position, on_delete=models.CASCADE)
    department = models.ForeignKey(Department, on_delete=models.CASCADE)

    class Meta:
        ordering = ['short_name']

    def __str__(self):
        return self.short_name


class Classroom(models.Model):
    center_number = models.IntegerField()
    classroom = models.IntegerField()
    num_seats = models.IntegerField(null=True)

    class Meta:
        unique_together = ('center_number', 'classroom')

    def __str__(self):
        return str(self.classroom)


class LessonTime(models.Model):
    lesson_number = models.IntegerField()
    start_time = models.TimeField(auto_now=False, auto_now_add=False)
    end_time = models.TimeField(auto_now=False, auto_now_add=False)

    def __str__(self):
        return str(self.lesson_number)


class Subgroup(models.Model):
    group = models.ForeignKey(Group, on_delete=models.CASCADE)
    subgroup_number = models.IntegerField()

    class Meta:
        ordering = ['group', 'subgroup_number']

    def __str__(self):
        return str(self.subgroup_number)


class Lesson(models.Model):
    week_number = models.IntegerField()
    weekday = models.ForeignKey(Weekday, on_delete=models.CASCADE)
    lesson_number = models.ForeignKey(LessonTime, on_delete=models.CASCADE)
    subgroup = models.ManyToManyField(Subgroup)
    discipline = models.ForeignKey(Discipline, on_delete=models.CASCADE)
    lesson_type = models.ForeignKey(LessonType, on_delete=models.CASCADE)
    teacher = models.ForeignKey(Teacher, on_delete=models.CASCADE)
    classroom = models.ForeignKey(Classroom, on_delete=models.CASCADE)
    start_date = models.DateField()
    end_date = models.DateField()

    class Meta:
        ordering = ['weekday']

    def __str__(self):
        return str(self.discipline)


class ExamTime(models.Model):
    start_time = models.TimeField()

    def __str__(self):
        return str(self.start_time)


class Exam(models.Model):
    lesson = models.OneToOneField(Lesson, on_delete=models.CASCADE)
    exam_date = models.DateField()
    start_time = models.ForeignKey(ExamTime, on_delete=models.CASCADE)

    class Meta:
        ordering = ['exam_date', 'start_time']

rasp/check/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.http import FileResponse
from django.contrib.admin.views.decorators import staff_member_required
from django.core.files.storage import FileSystemStorage
from .models import MyFiles
from .utils import parser_class_rasp_xls, parser_exam_rasp, parser_sved, parser_workload, check_xml_class, \
    check_xml_exam, class_to_db, exam_to_db
from django.conf import settings
import os


@staff_member_required
def load_file_get(request):
    # Обработка GET запроса
    return render(request, 'check/load_file.html')


@staff_member_required
def load_file_post(request):
    file = request.FILES.get('file')
    category = request.POST.get('type')  # Получаем выбранную категорию из формы
    semester = request.POST.get('semester')
    year = request.POST.get('year')
    directories = {
        'autumn_spring': [
            os.path.join(settings.MEDIA_ROOT, 'upl_files', f'{year}_autumn'),
            os.path.join(settings.MEDIA_ROOT, 'upl_files', f'{year}_spring')
        ],
        'autumn': os.path.join(settings.MEDIA_ROOT, 'upl_files', f'{year}_autumn'),
        'spring': os.path.join(settings.MEDIA_ROOT, 'upl_files', f'{year}_spring')
    }
    pdf_directories = {
        'class_pdf': os.path.join(settings.MEDIA_ROOT, 'pdf_files', f'{year}_{semester}'),
        'exam_pdf': os.path.join(settings.MEDIA_ROOT, 'pdf_files', f'{year}_{semester}')
    }
    if file is not None and category != 'empty' and semester in directories and year != 'empty':
        if category in ['class_pdf', 'exam_pdf']:
            fs = FileSystemStorage(location=pdf_directories[category])
            filename = fs.save(file.name, file)
            MyFiles.objects.create(file=filename, file_type=category, year=year, semester=semester,
                                   directory_path=pdf_directories[category])
        else:
            if isinstance(directories[semester], list):
                for directory in directories[semester]:
                    fs = FileSystemStorage(location=directory)
                    filename = fs.save(file.name, file)
                    MyFiles.objects.create(file=filename, file_type=category, year=year, semester=semester, directory_path = directory)
            else:
                fs = FileSystemStorage(location=directories[semester])
                filename = fs.save(file.name, file)
                MyFiles.objects.create(file=filename, file_type=category, year=year, semester=semester, directory_path=directories[semester])
    return render(request, 'check/load_file.html')


@staff_member_required
def list_folders(request):
    folder_path = os.path.join(settings.MEDIA_ROOT, 'upl_files')
    folders = [name for name in os.listdir(folder_path) if os.path.isdir(os.path.join(folder_path, name))]
    return render(request, 'check/list_folders.html', {'folders': folders})


@staff_member_required
def list_files(request, folder):

    folder_path = os.path.join(settings.MEDIA_ROOT, 'upl_files', folder)
    if os.path.exists(folder_path) and os.path.isdir(folder_path):
        year, semester = folder.split('_')
        files = [{'folder': folder, 'file_name': f, 'year': year, 'semester': semester} for f in os.listdir(folder_path)
                 if os.path.isfile(os.path.join(folder_path, f))]

        my_files = []

        for file_info in files:
            my_file = MyFiles.objects.filter(file__endswith=file_info['file_name']).filter(
                file_type__in=['class_rasp', 'exam_rasp']).first()

            if my_file:
                my_file.file_name = file_info['file_name']
                my_file.year = file_info['year']
                my_file.semester = file_info['semester']

                if my_file.file_type == 'class_rasp':
                    my_file.name_button = 'Проверить расписание занятий'
                elif my_file.file_type == 'exam_rasp':
                    my_file.name_button = 'Проверить расписание экзаменов'

                my_files.append(my_file)
        return render(request, 'check/list_files.html', {'folder': folder, 'files': files, 'my_files': my_files})
    else:
        return HttpResponse("Директория не найдена")


@staff_member_required
def download_file(request, folder, filename):
    file_path = os.path.join(settings.MEDIA_ROOT, 'upl_files', folder, filename)
    if os.path.exists(file_path) and os.path.isfile(file_path):
        return FileResponse(open(file_path, 'rb'), as_attachment=True)
    else:
        return HttpResponse("Файл не найден")


@staff_member_required
def download_file_xml(request, folder, filename):
    file_path = os.path.join(settings.MEDIA_ROOT, 'create_xml', folder, filename)
    if os.path.exists(file_path) and os.path.isfile(file_path):
        return FileResponse(open(file_path, 'rb'), as_attachment=True)
    else:
        return HttpResponse("Файл не найден")


@staff_member_required
def report(request, folder):
    folder_path = os.path.join(settings.MEDIA_ROOT, 'create_xml', folder)
    files = []

    my_files = MyFiles.objects.filter(directory_path=folder_path, file_type='success').values_list('file', flat=True)
    print(my_files)

    if os.path.exists(folder_path) and os.path.isdir(folder_path):
        for filename in os.listdir(folder_path):
            if filename == 'report_class_rasp.xml' or filename == 'report_exam_rasp.xml':
                files.append(filename)

    return render(request, 'check/report.html', {'folder': folder, 'files': files, 'my_files': my_files})


@staff_member_required
def rasp_to_db(request):
    file_name = request.GET.get('file_name')  # название report
    folder = request.GET.get('folder')
    year_semester = folder.split('_')
    year = year_semester[0]
    semester = year_semester[1]
    my_file = MyFiles.objects.filter(file=file_name, year=year, semester=semester).first()
    directory_path = my_file.directory_path  # путь до xml

    if file_name == 'report_class_rasp.xml':
        class_to_db(directory_path, year, semester)
    elif file_name == 'report_exam_rasp.xml':
        exam_to_db(directory_path, year, semester)

    return render(request, 'check/rasp_to_db.html')


@staff_member_required
def schedule_check(request, folder):
    filename = request.GET.get('filename', None)
    type_file = request.GET.get('file_type', None)
    year, semester = folder.split('_')
    file_semester = semester
    print(type_file)
    folder_path = os.path.join(settings.MEDIA_ROOT, 'upl_files', folder)
    file_path = os.path.join(folder_path, filename)
    my_files = MyFiles.objects.filter(directory_path=folder_path)
    # создание всех xml
    output_folder = None
    report_name = None
    parsed_data = []

    if type_file == 'class_rasp':
        output = parser_class_rasp_xls(file_path, filename, folder, type_file)
        if output:
            output_folder = output[0]
            folder = output[1]
        print('filename')
        print(filename)
    elif type_file == 'exam_rasp':
        output = parser_exam_rasp(file_path, filename, folder, type_file)
        if output:
            output_folder = output[0]
            folder = output[1]
        print('filename')
        print(filename)

    for file in my_files.values():
        file_path = os.path.join(file['directory_path'], file['file'])
        print('file_path')
        print(file_path)
        file_type = file['file_type']

        if file_type == 'sved':
            parsed_data.append(parser_sved(file_path, folder, file_type))
        elif file_type == 'workload':
            parsed_data.append(parser_workload(file_path, folder, file_type, file_semester))

    # проведение проверки определенного расписания
    for file in my_files.values():
        file_path = os.path.join(file['directory_path'], file['file'])
        print('Проверка xml')
        print(file['file'])
        file_type = file['file_type']

        if file_type == type_file:
            if file_type == 'class_rasp':
                report_name = check_xml_class(output_folder, folder)
            elif file_type == 'exam_rasp':
                report_name = check_xml_exam(output_folder, folder)

    return render(request, 'check/schedule_check.html', {'folder': folder, 'report_name': report_name})

rasp/check/templates/check/list_files.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    {% load static %}
    <link rel="stylesheet" href="{% static 'check/style.css' %}">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Список файлов в семестре "{{ folder }}"</title>
</head>
<body>
    <div class="container">
        <header>
            {% include 'check/navbar.html' %}

            <h1 class="text-center">Список файлов в семестре "{{ folder }}"</h1>
            <a href="/check/list_folders" class="back-link">Назад</a>
        </header>
        <ul class="list-group">
            {% for file in files %}
            <li class="list-group-item">
                <a href="{% url 'check:download_file' folder=folder filename=file.file_name %}">{{ file.file_name }}</a>
                {% for my_file in my_files %}
                    {% if file.file_name == my_file.file_name %}
                        {% if files|length > my_files|length %}
                            <a href="{% url 'check:schedule_check' folder=folder %}?filename={{ file.file_name }}&
                            year={{ file.year }}&semester={{ file.semester }}&file_type={{ my_file.file_type }}"
                               class="btn btn-xml">{{ my_file.name_button }}</a>
                        {% endif %}
                    {% endif %}
                {% endfor %}
                <br>

            </li>
            {% endfor %}
        </ul>

        <a href="{% url 'check:report' folder=folder %}" class="btn btn-primary">Перейти к отчетам</a>

    </div>
</body>


</html>

rasp/check/templates/check/list_folders.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    {% load static %}
    <link rel="stylesheet" href="{% static 'check/style.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Загруженные файлы</title>
</head>
<body>
    <div class="container">
        <header>
            {% include 'check/navbar.html' %}
            <h1>Семестры</h1>
        </header>
        <ul class="list-group">
        {% for folder in folders %}
            <li class="list-group-item"><a href="{% url 'check:list_files' folder=folder %}">{{ folder }}</a></li>
        {% endfor %}
        </ul>
    </div>
</body>
</html>

rasp/check/templates/check/load_file.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width-device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'check/style.css' %}">
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script> <!-- для вывода года в списке -->

    <title>Check Page</title>
</head>
<body>
    <div class="container">
    <header>
        {% include 'check/navbar.html' %}
        <h1 class="text-center">Загрузка файлов</h1>
    </header>
        <div class="container-info">
            <form method="POST" action="{% url 'check:check_page_post' %}" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="mb-3">
                    <label for="formFileMultiple" class="form-label"></label>
                    <div class="input-group">
                        <input name="file" class="form-control" type="file" id="formFileMultiple" multiple directory>
                    </div>
                </div>
                <div class="mb-3">
                    <label for="type" class="form-label">Выберите тип файла</label>
                    <select name="type" class="form-select" id="type">
                        <option value="empty"></option>
                        <option value="class_rasp">Расписание занятий</option>
                        <option value="exam_rasp">Расписание экзаменов</option>
                        <option value="sved">Сведения к составлению расписания</option>
                        <option value="workload">Нагрузка преподавателей</option>
                        <option value="class_pdf">Расписание занятий PDF</option>
                        <option value="exam_pdf">Расписание экзаменов PDF</option>
                    </select>
                </div>
                <div class="mb-3">
                    <label for="semester" class="form-label">Выберите семестр</label>
                    <select name="semester" class="form-select" id="semester">
                        <option value="empty"></option>
                        <option value="autumn">Осенний</option>
                        <option value="spring">Весенний</option>
                        <option value="autumn_spring">Осенний и весенний</option>
                    </select>
                </div>
                <div class="mb-3">
                    <label for="year" class="form-label">Выберите учебный год</label>
                    <select name="year" class="form-select" id="year">
                        <option value="category1"></option>
                        <!-- Добавьте другие категории по аналогии -->
                    </select>
                </div>
                <button type="submit" class="btn btn-primary">Загрузить</button>
            </form>
        </div>
    </div>

    <!-- для вывода года в списке -->
    <script>
        var select = $("#year");
        var currentYear = new Date().getFullYear() - 1;
        var numberOfYears = 10;

        for (var i = 0; i < numberOfYears; i++) {
            var year = currentYear + i;
            var nextYear = year + 1;
            select.append($("<option></option>").attr("value", year + "-" + nextYear).text(year + "-" + nextYear));
        }
    </script>
</body>
</html>

rasp/check/templates/check/navbar.html
{% load static %}
    <link rel="stylesheet" href="{% static 'check/style.css' %}">
<nav class="navbar navbar-expand-lg">
    <div class="container-fluid">
        <a class="navbar-brand" href="/admin">Главная</a>
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="/check/load">Загрузка файлов</a>
            </li>
            <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="/check/list_folders">Проверка расписания</a>
            </li>
        </ul>
    </div>
</nav>

rasp/check/templates/check/rasp_to_db.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    {% load static %}
    <link rel="stylesheet" href="{% static 'check/style.css' %}">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Отчеты "{{ folder }}"</title>
</head>
<body>
    <div class="container">
        <header>
            {% include 'check/navbar.html' %}
            <h1>Расписание успешно загружено!</h1>
            <a href="/check/list_folders" class="back-link">Назад</a>
        </header>
    </div>
</body>

rasp/check/templates/check/report.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    {% load static %}
    <link rel="stylesheet" href="{% static 'check/style.css' %}">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Отчеты "{{ folder }}"</title>
</head>
<body>
    <div class="container">
        <header>
            {% include 'check/navbar.html' %}
            <h1>Список отчетов в "{{ folder }}"</h1>
            <a href="/check/list_files/{{ folder }}" class="back-link">Назад</a>
        </header>
            {% if files %}
                <ul class="list-group">
                    {% for file in files %}
                        <li class="list-group-item">
                            <a href="{% url 'check:download_file_xml' folder=folder filename=file %}">{{ file }}</a>
                            {% for my_file in my_files %}
                                {% if my_file == file %}
                                    <a href="{% url 'check:rasp_to_db' %}?file_name={{ my_file }}&folder={{ folder }}"
                                       class="btn btn-xml">Загрузить в бд</a> {{ report_success }}
                                {% endif %}
                            {% endfor %}
                        </li>
                    {% endfor %}
                </ul>
            {% else %}
                <h5>Файлы отсутствуют</h5>
            {% endif %}

    </div>
</body>
</html>

rasp/check/templates/check/schedule_check.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    {% load static %}
    <link rel="stylesheet" href="{% static 'check/style.css' %}">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Проверка расписания</title>
</head>
<body>
    <div class="container">
        <header>
            {% include 'check/navbar.html' %}
            <h1>Результат проверки</h1>
            <a href="{% url 'check:list_files' folder=folder %}" class="back-link">Назад</a>
        </header><br>
        <div>
            <h5>Скачать отчет:</h5>
            <ul class="list-group">
                <li class="list-group-item">
                    <a href="{{ settings.MEDIA_URL }}create_xml/{{ folder }}/{{ report_name }}" download>{{ report_name }}</a></li>
                </li>
            </ul>
        </div>

    </div>
</body>
</html>